### ISSUE TITLE
z fighting issue between road decals and road

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [MicroGSD/RoadArchitect#67] opened 2019-01-21 17:12 UTC
first every thing is working really good in editor. but having issues in mobile.
Using the released version (https://github.com/MicroGSD/RoadArchitect/releases)
1- z fighting issue between road decals and road
2- road decals shows only few meters from camera. beyond that is seeing really bad blur.(which look worse when driving truck)
3- overall road sides ( where road shoulders ends)(don't know if its related to RA. ignore this if irrelevant.)
![screenshot_20190121-220538](https://user-images.githubusercontent.com/32755091/51489170-64e6f380-1dc9-11e9-9ecf-45c938178f0f.jpg)
![screenshot_20190121-220415](https://user-images.githubusercontent.com/32755091/51489171-657f8a00-1dc9-11e9-98e0-72b6043d7031.jpg)
![screenshot_20190121-220603](https://user-images.githubusercontent.com/32755091/51489172-657f8a00-1dc9-11e9-830f-1846a5eaef04.jpg)

this is my first time using RA. so i will be thankful for any support from community.
Thank you.

**Comment by embeddedt** [comment] 2019-01-21 17:38
Try my version of RoadArchitect. It should have a fix for this issue.

**Comment by MuhammadWaqasOfficial** [comment] 2019-01-21 17:42
okay sir.
thank you for support.

**Comment by MuhammadWaqasOfficial** [comment] 2019-01-22 07:18
> Try my version of RoadArchitect. It should have a fix for this issue.

unreleased version (github.com/MicroGSD/RoadArchitect & github.com/embeddedt/RoadArchitect)   have issue of road markings. it is not making road lanes (road marker). after one line of road lane it is stretched i guess.
See images
![issue2](https://user-images.githubusercontent.com/32755091/51518269-2d1a9300-1e3f-11e9-82f3-0ac17ced9523.png)
![heirarchy](https://user-images.githubusercontent.com/32755091/51518270-2d1a9300-1e3f-11e9-952e-7ae21c14254c.png)
![issue1](https://user-images.githubusercontent.com/32755091/51518271-2d1a9300-1e3f-11e9-98b2-08e0b54797aa.png)

**Comment by embeddedt** [comment] 2019-01-22 12:16
I think @Zireael07 is correct. I have used my version of RoadArchitect on many platforms and several versions of Unity and I don't see this issue. Maybe your quality settings are set too low.

**Comment by embeddedt** [comment] 2019-01-22 12:42
@MuhammadWaqasOfficial I made a simple scene with those quality settings and I can't reproduce the issue.

**Comment by djohns451** [comment] 2019-01-22 15:57
@Zireael07 Anisotropy changes were pushed a bit back. As long as you are
using the latest commit, it shouldn't be an issue.

**Comment by embeddedt** [comment] 2019-01-22 16:32
@djohns451 I think this is a different issue. The other problem was because the mipmaps were being generated incorrectly, resulting in blurry and invisible road lines **at a distance**. Here we are seeing blurry lines when there is barely any distance between the camera and the road:

![](https://user-images.githubusercontent.com/32755091/51518271-2d1a9300-1e3f-11e9-98b2-08e0b54797aa.png)

**Comment by MuhammadWaqasOfficial** [comment] 2019-01-24 08:55
thank you guys for responding and supporting.
z fighting issue is resolve. what i find out in my case is clipping planes (near) problem. i decrease the value to 0.01f which cause the problem. i change the value and it resolve.
now RA looking really great with my unfinished environment.

**Comment by MuhammadWaqasOfficial** [comment] 2019-01-24 09:07
road markers appear correctly.
one thing more, road markers texture stretching issue appears only in unity( 2018.1.0f2) for me. road markers showing correctly in mobile build.

Thank you Again

**Comment by embeddedt** [comment] 2019-01-24 15:46
@MuhammadWaqasOfficial The texture stretching sounds like a project-specific issue, since I can't seem to make it happen over here. So I will close this issue. Glad to hear it is working now.

**Closed by embeddedt** 2019-01-24 15:46 UTC
