### ISSUE TITLE
Height Match Not Working On Really Big Terrain (25000 x 25000)( Heightmap 129)

### ISSUE THREAD

**Issue by MuhammadWaqasOfficial** [MicroGSD/RoadArchitect#63] opened 2019-01-03 13:05 UTC
I have really big terrain 25000x25000 with heightmap of 129. Tool works fine with low width,length terrain but have issue with height match. when i lift the nodes or make new nodes, terrain wont affected only roads mesh updates.

**Comment by embeddedt** [comment] 2019-01-03 13:09
@MuhammadWaqasOfficial I can't recall the discussion but I think RoadArchitect doesn't work or has major problems when using really large terrains. Can you try it with a smaller terrain (maybe 10000x10000) and see if the issue goes away?

**Comment by MuhammadWaqasOfficial** [comment] 2019-01-03 13:12
yes it work fine with 10000x10000

**Comment by embeddedt** [comment] 2019-01-03 13:22
@MuhammadWaqasOfficial I will try and reproduce the issue on my end later. In the meantime please check that height modification is enabled for the road.

**Comment by embeddedt** [comment] 2019-01-03 13:51
@MuhammadWaqasOfficial I can't reproduce the issue. Can you create a small test scene to reproduce it?

**Comment by MuhammadWaqasOfficial** [comment] 2019-01-03 13:57
okay thank you.
downloading and checking.
previously i download this unity package
https://github.com/MicroGSD/RoadArchitect/releases

**Comment by MuhammadWaqasOfficial** [comment] 2019-01-04 08:05
no success with this also.
i guess i have to use multiple terrains instead of single terrain.
thank you for support sir.

**Comment by Flavelius** [comment] 2019-01-12 14:38
129 is way way way way too small for a terrain this size and that's very likely the problem, not enough resolution to adapt.

**Comment by MuhammadWaqasOfficial** [comment] 2019-01-12 14:42
hmmmm. 
what should i do now? 
what value you think is good for that big terrain?

**Comment by embeddedt** [comment] 2019-01-12 15:33
@Flavelius Thanks. That makes a lot of sense. The problem I found is that Unity heightmaps can't be bigger than  4097, and when I used 4097 the editor grew very slow and eventually crashed. (I hadn't even put a road on the terrain yet.)

**Comment by Flavelius** [comment] 2019-01-12 15:54
Do it any big game does it, split the terrain into many small pieces that in turn can then even have high resolution maps and stream them in. The new terrain system (2018.3 even has built-in features to create and connect those tiles)

**Comment by MuhammadWaqasOfficial** [comment] 2019-01-12 16:00
okay sir

**Comment by nonbinary-duck** [comment] 2019-02-14 08:11
If you honestly do need 25x25k of terrain I would recommend breaking it down into 2x2k chunks (which would make a sh*t ton of tiles) and then making a script that unloads and loads them in if the camera isn't facing them of if they're obscured by the cameras view range. Even having 9 2x2k tiles at 2048x2048 height and splat will drop a modern card down to 40fps so you would defo need the loading/unloading system. Also, you may want to make sure that your trees have a culled section on their LOD

**Comment by tonygod** [comment] 2019-02-23 19:40
Because the Transform class in Unity uses type float in the Vector3 class for position and rotation, terrain sizes and positions beyond 10K will result in inaccurate mathematical calculations that will cause all kinds of things to be off in your project.  As suggested, stick with smaller terrain (and mesh) chunks and have a system for keeping everything within 10K distance at all times.

I recommend this issue is closed as this is not a supported scenario.

**Closed** 2019-02-23 19:47 UTC
