### ISSUE TITLE
T-Junction

### ISSUE THREAD

**Issue by botiapa** [MicroGSD/RoadArchitect#48] opened 2018-04-12 19:30 UTC
Can I create a T-junction with RoadaRchitect? Any help would be appreciated.

**Comment by botiapa** [comment] 2018-04-15 19:16
How could I fix that?

**Comment by ArtyIF** [comment] 2018-05-04 18:32
This is a known issue. It's been there forever.

**Comment by djohns451** [comment] 2018-05-05 04:45
Yeah, it's something we're working on, but so far the code assumes the
intersection is between roads of equal lane counts.

**Comment by botiapa** [comment] 2018-05-05 17:34
Then, is there any workaround to this?

**Comment by ArtyIF** [comment] 2018-05-06 06:03
well you can connect the ends of roads with different count of lanes. create a 4-lane road, make an intersection with another one and then connect the ends with 2-lane oneOn May 5, 2018 20:34, killswitch <notifications@github.com> wrote:Then, is there any workaround to this?

**Comment by djohns451** [comment] 2018-05-06 06:08
Yeah, that works for now, it's a bit of a hack, though.

**Comment by botiapa** [comment] 2018-05-06 10:52
Okay, thanks for the help. I don't know if I should close this issue, as it isn't fixed. I think it's better if I leave this choice to the admin.

**Comment by tonygod** [comment] 2018-07-06 22:36
This is a duplicate of #23

**Closed by tonygod** 2018-07-06 22:36 UTC
